### ISSUE TITLE
OOM...

### ISSUE THREAD

**Issue by C-water** [likesum/bpn#2]
Hi, 
When I was processing the 1024*1536 image, the system indicated OOM.  What is the size of the feature map you processed before?
The problem might be multiplying basis and coeff, but I haven't been able to solve it yet....

**Comment by likesum** [comment]
The testing code in the repo divides images to patches and denoise. It should be able to handle large images without running into OOM (assuming extracting and grouping patches won't take too much memory). If you are trying to process your image as a whole, then an 1024*1536 image will likely cause OOM.
